version: "3.9"
services:
  smartpay-postgres:
    container_name: smartpay-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: smartpay_dev
      POSTGRES_USER: smartpay_dev
      POSTGRES_PASSWORD: smartpay_dev
    ports:
      - "5432:5432"
    volumes:
      - '/data/smartpay-postgres:/var/lib/postgresql/data'
